#include <assert.h>
#include <WindowsX.h>
#include <tchar.h>
#include "hge.h"
#include "utils.h"
#include "constdefines.h"
#include "ResourceManager.h"
#include "ConfigManager.h"
#include "IDdefines.h"